### GET /
GET http://localhost:5000

### Register a user POST /auth/register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Login a user POST /auth/login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "gilgamesh@gmail.com",
    "password": "123123123"
}

### Fetch all todos GET/Todos (protected)
GET http://localhost:5000/todos 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4OTc1Nzk0LCJleHAiOjE3NDkwNjIxOTR9.ca86i8iiqqsu9qiWKGjRwq73Uf-aMI_47VIVQl-tKEg


### Create a new todo POST/Todo (protected)
POST http://localhost:5000/todos 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4OTc1Nzk0LCJleHAiOjE3NDkwNjIxOTR9.ca86i8iiqqsu9qiWKGjRwq73Uf-aMI_47VIVQl-tKEg
Content-Type: application/json

{
    "task": "Finish coding the projets"
}

### Update a todo PUT/TODOS/ID (proteted)
PUT http://localhost:5000/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4OTc1Nzk0LCJleHAiOjE3NDkwNjIxOTR9.ca86i8iiqqsu9qiWKGjRwq73Uf-aMI_47VIVQl-tKEg
Content-Type: application/json

{
    "completed": 1
}
### Delete a todo DELETE/TODOS/ID (proteted)
DELETE http://localhost:5000/todos/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzQ4OTc1Nzk0LCJleHAiOjE3NDkwNjIxOTR9.ca86i8iiqqsu9qiWKGjRwq73Uf-aMI_47VIVQl-tKEg

